# Generated by Django 6.0.2 on 2026-02-19 09:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("datetime", models.DateTimeField(verbose_name="Дата и время")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("waiting", "Ожидание"),
                            ("accepted", "Принят"),
                            ("done", "Завершён"),
                            ("cancelled", "Отменён"),
                        ],
                        default="waiting",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                ("complaint", models.TextField(verbose_name="Жалоба")),
                (
                    "doctor_note",
                    models.TextField(blank=True, verbose_name="Заметка врача"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appointments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пациент",
                    ),
                ),
            ],
            options={
                "verbose_name": "Запись на приём",
                "verbose_name_plural": "Записи на приём",
                "ordering": ["datetime"],
            },
        ),
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(verbose_name="Текст сообщения")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "is_read",
                    models.BooleanField(default=False, verbose_name="Прочитано"),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_messages",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пациент",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_messages",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Отправитель",
                    ),
                ),
            ],
            options={
                "verbose_name": "Сообщение",
                "verbose_name_plural": "Сообщения",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="HealthLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Дата")),
                (
                    "weight",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=5,
                        null=True,
                        verbose_name="Вес (кг)",
                    ),
                ),
                (
                    "systolic",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Давление систолическое"
                    ),
                ),
                (
                    "diastolic",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Давление диастолическое"
                    ),
                ),
                (
                    "blood_sugar",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=4,
                        null=True,
                        verbose_name="Сахар крови (ммоль/л)",
                    ),
                ),
                ("note", models.TextField(blank=True, verbose_name="Заметка")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="health_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пациент",
                    ),
                ),
            ],
            options={
                "verbose_name": "Запись дневника здоровья",
                "verbose_name_plural": "Дневник здоровья",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="PatientProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "iin",
                    models.CharField(max_length=12, unique=True, verbose_name="ИИН"),
                ),
                (
                    "phone",
                    models.CharField(blank=True, max_length=20, verbose_name="Телефон"),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Адрес (село/участок)"
                    ),
                ),
                (
                    "date_of_birth",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата рождения"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="patient_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Профиль пациента",
                "verbose_name_plural": "Профили пациентов",
            },
        ),
        migrations.CreateModel(
            name="TestResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "indicator",
                    models.CharField(
                        max_length=100,
                        verbose_name="Показатель (глюкоза, давление и т.д.)",
                    ),
                ),
                ("value", models.CharField(max_length=50, verbose_name="Значение")),
                (
                    "unit",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="Единица измерения"
                    ),
                ),
                (
                    "norm",
                    models.CharField(blank=True, max_length=50, verbose_name="Норма"),
                ),
                ("date", models.DateField(verbose_name="Дата")),
                (
                    "added_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="added_results",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Добавил",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="test_results",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пациент",
                    ),
                ),
            ],
            options={
                "verbose_name": "Результат анализа",
                "verbose_name_plural": "Результаты анализов",
                "ordering": ["-date"],
            },
        ),
    ]
